version: '3'
services:
  web:
    build: .
    ports:
    - "8000:8000"
    links:
    - poker
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_HOST: 10.13.37.1
      DB_NAME: xmppoke
      DB_USER: xmppoke
  poker:
    image: xsfjonas/xmppoke-docker
